// import type { Ability } from "@scobit/types";

// export const testAbilities: Ability[] = [
//   {
//     a_id: "ab-001",
//     t_id: "team-a",
//     u_id: "user-001",
//     avr: 0.150,
//     hr_per_game: 0.0,
//     steal_per_game: 0.0,
//     err_per_game: 0.8,
//     throw_distance: 40,
//     sprint_sec: 8.5,
//   },
//   {
//     a_id: "ab-002",
//     t_id: "team-a",
//     u_id: "user-002",
//     avr: 0.200,
//     hr_per_game: 0.02,
//     steal_per_game: 0.05,
//     err_per_game: 0.6,
//     throw_distance: 50,
//     sprint_sec: 8.0,
//   },
//   {
//     a_id: "ab-003",
//     t_id: "team-a",
//     u_id: "user-003",
//     avr: 0.230,
//     hr_per_game: 0.05,
//     steal_per_game: 0.1,
//     err_per_game: 0.4,
//     throw_distance: 60,
//     sprint_sec: 7.5,
//   },
//   {
//     a_id: "ab-004",
//     t_id: "team-b",
//     u_id: "user-004",
//     avr: 0.260,
//     hr_per_game: 0.1,
//     steal_per_game: 0.2,
//     err_per_game: 0.3,
//     throw_distance: 70,
//     sprint_sec: 7.0,
//   },
//   {
//     a_id: "ab-005",
//     t_id: "team-b",
//     u_id: "user-005",
//     avr: 0.290,
//     hr_per_game: 0.2,
//     steal_per_game: 0.3,
//     err_per_game: 0.2,
//     throw_distance: 80,
//     sprint_sec: 6.6,
//   },
//   {
//     a_id: "ab-006",
//     t_id: "team-c",
//     u_id: "user-006",
//     avr: 0.320,
//     hr_per_game: 0.35,
//     steal_per_game: 0.5,
//     err_per_game: 0.15,
//     throw_distance: 90,
//     sprint_sec: 6.2,
//   },
//   {
//     a_id: "ab-007",
//     t_id: "team-c",
//     u_id: "user-007",
//     avr: 0.350,
//     hr_per_game: 0.5,
//     steal_per_game: 0.7,
//     err_per_game: 0.1,
//     throw_distance: 100,
//     sprint_sec: 5.9,
//   },
//   {
//     a_id: "ab-008",
//     t_id: "team-pro",
//     u_id: "user-008",
//     avr: 0.380,
//     hr_per_game: 0.7,
//     steal_per_game: 1.0,
//     err_per_game: 0.05,
//     throw_distance: 110,
//     sprint_sec: 5.6,
//   },
// ];
// export default testAbilities;