import { AdminCreateNewTeam } from "@func/admin/createTeam";
import { AdminGameInit } from "@func/admin/game/index.js";
import { AdminGameEditInit, editGame, editScores } from "@func/admin/gameEdit/index.js";
import { AddNewGame, AdminGamesInit } from "@func/admin/Games/index.js";
import { kojinAccountRegistGameInit, registNewGameForKojin, updateGameForKojinAccount } from "@func/admin/kojinGameKanri";
import { AdminMemberInit, AdminMemberInitForKojin, updateMember, updateMemberForKojin } from "@func/admin/member/index.js";
import { AdminMembersInit, MembersAddMember } from "@func/admin/members/index.js";
import { editAccount, mypageFetchKojinData, mypageFetchTeams, mypageSelectTeam } from "@func/admin/mypage/index.js";
import { AdminScoresPerMember } from "@func/admin/score";
import { AdminTeamInit, updateTeamInfo } from "@func/admin/team/index.js";
import { Router } from "src/Router/router.js";

export const adminRouter = new Router();

adminRouter.post('/mypage/teams', mypageFetchTeams);
adminRouter.post('/mypage/select', mypageSelectTeam);
adminRouter.post('/mypage/kojin', mypageFetchKojinData);
adminRouter.post('/team/init', AdminTeamInit);
adminRouter.post('/team/update', updateTeamInfo);
adminRouter.post('/team/new', AdminCreateNewTeam);
adminRouter.post('/members/init', AdminMembersInit);
adminRouter.post('/members/add', MembersAddMember);
adminRouter.post('/member/init', AdminMemberInit);
adminRouter.post('/member/update', updateMember);
adminRouter.post('/account/edit', editAccount);
adminRouter.post('/games/init', AdminGamesInit);
adminRouter.post('/games/new', AddNewGame);
adminRouter.post('/game/init', AdminGameInit);
adminRouter.post('/game/new/kojin/init', kojinAccountRegistGameInit);
adminRouter.post('/game/new/kojin/add', registNewGameForKojin);
adminRouter.post('/game/update/kojin', updateGameForKojinAccount);
adminRouter.post('/game/edit/init', AdminGameEditInit);
adminRouter.post('/game/edit/update', editGame);
adminRouter.post('/score/init', AdminScoresPerMember);
adminRouter.post('/scores/update', editScores);
adminRouter.post('/member/kojin/init', AdminMemberInitForKojin);
adminRouter.post('/member/kojin/update', updateMemberForKojin);